<?php
/**
 * @file
 * Xeditor module file.
 */


/**
 * Implements hook_init().
 */
function xeditor_core_init() {
  // Get all loaded javascript.
  $scripts = drupal_add_js();

  // Extend edit module edit.js functionality.
  $js_files = array('xeditor.js', 'jquery.selection.js');
  $js_dir = drupal_get_path('module', 'xeditor_core') . '/js/';
  $counter = 1;
  foreach ($js_files as $js_file) {
    drupal_add_js($js_dir . $js_file, array(
      'scope' => 'footer',
      'group' => JS_THEME,
      'every_page' => TRUE,
      'weight' => -$counter,
    ));
    $counter++;
  }

  // Pre-load the ckeditor.js for manipulating user selection.
  if (!in_array('profiles/xeditor/libraries/ckeditor/ckeditor.js', $scripts)) {
    drupal_add_js('profiles/xeditor/libraries/ckeditor/ckeditor.js', array(
      'scope' => 'footer',
      'group' => JS_THEME,
      'every_page' => TRUE,
      'weight' => -3,
    ));
  }
  // CSS file for Barley-like feel.
  drupal_add_css(drupal_get_path('module', 'xeditor_core') . '/css/xeditor.css');
}
