<?php
/**
 * @file
 * Xeditor module file.
 */


/**
 * Implements hook_ckeditor_plugin().
 */
function xeditor_core_ckeditor_plugin() {
  return array(
    'ckeditor_selection' => array(
      // Name of the plugin used to write it.
      'name' => 'selection',
      // Description of the plugin it would be displayed in
      // the plugins management section of profile settings.
      'desc' => t('Manage selection'),
      // The full path to the CKEditor plugins
      // directory, with the trailing slash.
      'path' => drupal_get_path('module', 'xeditor_core') . '/ckeditor/selection/',
      'buttons' => array(
        'selection' => array(
          'icon' => 'icons/selection.png',
          'label' => 'Manage Selection',
        ),
      ),
    ),
  );
}


/**
 * Implements hook_init().
 */
function xeditor_core_init() {
  // Get all loaded javascript.
  $scripts = drupal_add_js();

  // Extend edit module edit.js functionality.
  $js_files = array('xeditor.js', 'jquery.selection.js');
  $js_dir = drupal_get_path('module', 'xeditor_core') . '/js/';
  $counter = 1;
  foreach ($js_files as $js_file) {
    drupal_add_js($js_dir . $js_file, array(
      'scope' => 'footer',
      'group' => JS_THEME,
      'every_page' => TRUE,
      'weight' => -$counter,
    ));
    $counter++;
  }

  // Pre-load the ckeditor.js for manipulating user selection.
  if (!in_array('profiles/xeditor/libraries/ckeditor/ckeditor.js', $scripts)) {
    drupal_add_js('profiles/xeditor/libraries/ckeditor/ckeditor.js', array(
      'scope' => 'footer',
      'group' => JS_THEME,
      'every_page' => TRUE,
      'weight' => -3,
    ));
  }
  // CSS file for Barley-like feel.
  drupal_add_css(drupal_get_path('module', 'xeditor_core') . '/css/xeditor.css');
}


/**
 * Implements hook_menu_alter().
 */
function xeditor_core_menu_alter(&$items) {
  // Add node "Revision" link in Contextual link.
  $items['node/%node/revisions']['type'] = MENU_LOCAL_ACTION;
  $items['node/%node/revisions']['context'] = MENU_CONTEXT_INLINE;
  return $items;
}
