<?php
/**
 * @file
 * Xeditor module file.
 */

module_load_include('inc', 'xeditor_core', 'xeditor_core_ajax');

/**
 * Implements hook_init().
 */
function xeditor_core_init() {
  global $base_url;

  // Get all loaded javascript.
  $scripts = drupal_add_js();

  // Extend edit module edit.js functionality.
  $js_files = array(
    'xeditor.js',
    'xeditor_core.js',
    'jquery.selection.js',
    'jquery.extends.js',
  );
  $js_dir = drupal_get_path('module', 'xeditor_core') . '/js/';
  $counter = 1;
  foreach ($js_files as $js_file) {
    drupal_add_js($js_dir . $js_file, array(
      'scope' => 'footer',
      'group' => JS_THEME,
      'every_page' => TRUE,
      'weight' => -$counter,
    ));
    $counter++;
  }

  // Pre-load the ckeditor.js for manipulating user selection.
  if (!in_array('profiles/xeditor/libraries/ckeditor/ckeditor.js', $scripts)) {
    drupal_add_js('profiles/xeditor/libraries/ckeditor/ckeditor.js', array(
      'scope' => 'footer',
      'group' => JS_THEME,
      'every_page' => TRUE,
      'weight' => -3,
    ));
  }
  // CSS file for Barley-like feel.
  drupal_add_css(drupal_get_path('module', 'xeditor_core') . '/css/xeditor.css');

  // Make sure that base_url is available on xeditor.js.
  drupal_add_js(array(
    'xeditor_core' => array('base_path' => $base_url),
  ), 'setting');
}


/**
 * Implements hook_menu().
 */
function xeditor_core_menu() {
  $items = array();

  $items['ajax-callback'] = array(
    'description' => 'Ajax handler for creating and editing of node.',
    'access arguments' => array('administer nodes'),
    'page callback' => '_xeditor_core_node_save',
    'title' => 'AJAX Handler',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Ajax handler for saving content.
 */
function _xeditor_core_node_save() {
  if (isset($_POST['nid']) && isset($_POST['content'])) {
    $nid = $_POST['nid'];
    $content = $_POST['content'];
    $node = node_load($nid);

    $node->body[$node->language][0]['value'] = $content;
    $node->log = "Updated the node " . $node->title;
    // Save node.
    node_save($node);
  }
}
